### ISSUE TITLE
The library cannot be build with Visual Studio 2013 U5

### ISSUE THREAD

**Issue by georgi-d** [cpp-netlib/uri#94]
The library cannot be build because of `constexpr` and `noexcept` direct usage instead of using the boost macros which handle this in a backward compatible way. 

Is it possible to reintroduce these macros or equivalent so the library can be consumed by Visual Studio 2013 U5?

**Comment by glynos** [comment]
The latest updates from a few months ago were intended to remove all dependencies on Boost (and anything else - this library only depends on the standard library). In order to do this, we decided to make the minimum supported compiler version as MSVC 2015. Clang and GCC have supported `constexpr` and `noexcept` for a number of years already.

I'll close this as won't fix, because the solution requires reintroducing dependencies.

**Comment by cxsup2** [comment]
Just ran into this limitiation. Maybe something like the following could be added to the root CMakeLists.txt file:

```
if(DEFINED MSVC_VERSION AND MSVC_VERSION LESS 1900)
   message(FATAL_ERROR "Requires VS 2015 or later...")
endif()

```

**Comment by glynos** [comment]
It's a quick fix, so I added it in the last commit (https://github.com/cpp-netlib/uri/commit/131037a937f8942dbe88966f269837f62b1f840e). Thanks for the suggestion.
